-- Order numbers: start at a random 5-digit base and increment from there.
--
-- `bookings.order_number` is `bigint generated by default as identity`, which
-- starts at 1 by default. This restarts the identity so the next order number
-- is a 5-digit value (40318, 40319, 40320, …). Run once in the Supabase SQL
-- editor. Existing test bookings keep their old low numbers — delete them from
-- the admin (Bookings → archive → "Delete all archived") before go-live.

ALTER TABLE public.bookings
  ALTER COLUMN order_number RESTART WITH 40318;
