-- ============================================================
--  Migration: add order_number + confirmation_number to bookings
--  Run once in the Supabase SQL editor on the existing project.
--  Safe to re-run (idempotent).
-- ============================================================

-- Sequential, human-friendly order number. Adding an identity column backfills
-- existing rows automatically and auto-assigns on every future insert.
alter table public.bookings
  add column if not exists order_number bigint generated by default as identity;

-- Random customer-facing confirmation code. The default expression is evaluated
-- per row, so existing rows are backfilled and new rows get one automatically.
alter table public.bookings
  add column if not exists confirmation_number text
    default ('BFX-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 8)));

-- Ensure no row is left without a code, then lock the column not-null + unique.
update public.bookings
  set confirmation_number =
        'BFX-' || upper(substr(md5(random()::text || id::text || clock_timestamp()::text), 1, 8))
  where confirmation_number is null;

alter table public.bookings
  alter column confirmation_number set not null;

create unique index if not exists bookings_confirmation_number_idx
  on public.bookings (confirmation_number);
